# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  username: <%= ENV['DATABASE_USERNAME'] || 'root' %>

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME_TEST'] || 'stripe_webhooks_test' %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
